import type { AppUser, Booking, Story, StoryTag, TravelPackage, TravelReview } from '@/types/travel';

export const mockStoryTags: Omit<StoryTag, 'storiesCount'>[] = [
  { id: 'tag-family',    slug: 'family',    label: 'Семейный отдых',      position: 1 },
  { id: 'tag-beach',     slug: 'beach',     label: 'Пляж и море',         position: 2 },
  { id: 'tag-mountains', slug: 'mountains', label: 'Горы и природа',      position: 3 },
  { id: 'tag-wellness',  slug: 'wellness',  label: 'Wellness и лечение',  position: 4 },
  { id: 'tag-active',    slug: 'active',    label: 'Активный отдых',      position: 5 },
  { id: 'tag-camp',      slug: 'camp',      label: 'Детский лагерь',      position: 6 },
  { id: 'tag-city',      slug: 'city',      label: 'Город и культура',    position: 7 },
  { id: 'tag-weekend',   slug: 'weekend',   label: 'Выходного дня',       position: 8 },
];

export const mockPackages: TravelPackage[] = [
  {
    id: 'pkg-bali-luxe',
    slug: 'bali-luxe-escape',
    title: 'Бали: Роскошный побег',
    destination: 'Убуд',
    country: 'Индонезия',
    summary: 'Частные виллы, ритуалы велнес и эксклюзивные впечатления острова для пар.',
    description:
      'Остановитесь на вилле у края джунглей, начинайте утра с сеансов велнес под руководством инструктора, а после обеда исследуйте водопады, рисовые террасы и пляжные клубы с личным водителем.',
    priceFrom: 1890,
    durationDays: 7,
    ratingAverage: 4.9,
    reviewCount: 38,
    heroImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1200&q=80'
    ],
    seatsLeft: 6,
    tags: ['warm', 'wellness', 'beach', 'couples'],
    isFeatured: true,
    createdAt: '2026-03-01T08:00:00.000Z',
    updatedAt: '2026-03-10T08:00:00.000Z'
  },
  {
    id: 'pkg-alps-premium',
    slug: 'swiss-alps-premium',
    title: 'Швейцарские Альпы: Премиум',
    destination: 'Церматт',
    country: 'Швейцария',
    summary: 'Железнодорожные приключения в горах, шале и альпийские виды открыточного качества.',
    description:
      'Премиальный маршрут, построенный вокруг живописных железнодорожных маршрутов, горных ужинов под руководством гида и гибких экскурсий как для искателей приключений, так и для неспешных путешественников.',
    priceFrom: 2390,
    durationDays: 6,
    ratingAverage: 4.8,
    reviewCount: 26,
    heroImage: 'https://images.unsplash.com/photo-1508261305436-e3f893cb0f3f?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=1200&q=80'
    ],
    seatsLeft: 4,
    tags: ['cold', 'mountains', 'luxury', 'winter'],
    isFeatured: true,
    createdAt: '2026-02-18T08:00:00.000Z',
    updatedAt: '2026-03-11T08:00:00.000Z'
  },
  {
    id: 'pkg-morocco-design',
    slug: 'morocco-design-journey',
    title: 'Марокко: Дизайн-путешествие',
    destination: 'Марракеш',
    country: 'Марокко',
    summary: 'Риады, ночи в пустыне и арт-впечатления в одном маршруте.',
    description:
      'С крыш медины до глэмпинга в Сахаре — этот маршрут сочетает архитектуру, кухню и мастер-классы с местными ремесленниками с достаточным количеством свободного времени для личного исследования.',
    priceFrom: 1490,
    durationDays: 8,
    ratingAverage: 4.7,
    reviewCount: 19,
    heroImage: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1489493887464-892be6d1daae?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1518544866330-95a6eb2e5e3a?auto=format&fit=crop&w=1200&q=80'
    ],
    seatsLeft: 9,
    tags: ['warm', 'culture', 'desert', 'food'],
    isFeatured: false,
    createdAt: '2026-02-25T08:00:00.000Z',
    updatedAt: '2026-03-05T08:00:00.000Z'
  },
  {
    id: 'pkg-iceland-fire-ice',
    slug: 'iceland-fire-ice',
    title: 'Исландия: Огонь и Лёд',
    destination: 'Рейкьявик',
    country: 'Исландия',
    summary: 'Гейзеры, ледники, северное сияние и вулканические пейзажи.',
    description:
      'Откройте для себя самый суровый и завораживающий уголок планеты. Ледники, горячие источники, водопады Скоугафосс и Сельяландсфосс, чёрные пляжи и незабываемое северное сияние над бескрайними полями лавы.',
    priceFrom: 2890,
    durationDays: 8,
    ratingAverage: 4.9,
    reviewCount: 22,
    heroImage: 'https://images.unsplash.com/photo-1504829857797-ddff29c27927?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1531168586646-a736fe579ffd?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1476611338391-6f395a0ebc7b?auto=format&fit=crop&w=1200&q=80'
    ],
    seatsLeft: 8,
    tags: ['cold', 'northern-lights', 'nature', 'active'],
    isFeatured: true,
    createdAt: '2026-02-10T08:00:00.000Z',
    updatedAt: '2026-03-08T08:00:00.000Z'
  },
  {
    id: 'pkg-thailand-islands',
    slug: 'thailand-golden-islands',
    title: 'Таиланд: Золотые острова',
    destination: 'Краби',
    country: 'Таиланд',
    summary: 'Изумрудные воды, белоснежные пляжи и лучший тайский сервис.',
    description:
      'Острова Пхи-Пхи, Краби и Ко-Ланта — три жемчужины Андаманского моря в одном маршруте. Снорклинг, морские каяки, традиционная тайская кухня и закаты, которые нельзя забыть.',
    priceFrom: 1290,
    durationDays: 10,
    ratingAverage: 4.8,
    reviewCount: 45,
    heroImage: 'https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80'
    ],
    seatsLeft: 12,
    tags: ['warm', 'beach', 'tropical', 'islands'],
    isFeatured: false,
    createdAt: '2026-01-20T08:00:00.000Z',
    updatedAt: '2026-03-01T08:00:00.000Z'
  },
  {
    id: 'pkg-norway-fjords',
    slug: 'norway-fjords-adventure',
    title: 'Норвегия: Мир фьордов',
    destination: 'Берген',
    country: 'Норвегия',
    summary: 'Трекинг, каяки и сказочные фьорды Скандинавии.',
    description:
      'Норвегия с её грандиозными фьордами — место для тех, кто ищет природу в её первозданном виде. Трекинг на Прекестулен, каяки по Согнефьорду, панорамная железная дорога Фломсбана и уютные норвежские деревушки.',
    priceFrom: 2190,
    durationDays: 9,
    ratingAverage: 4.7,
    reviewCount: 18,
    heroImage: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80'
    ],
    seatsLeft: 6,
    tags: ['cold', 'active', 'hiking', 'fjords', 'nature'],
    isFeatured: true,
    createdAt: '2026-02-05T08:00:00.000Z',
    updatedAt: '2026-03-09T08:00:00.000Z'
  }
];

export const mockReviews: TravelReview[] = [
  {
    id: 'rev-1',
    packageId: 'pkg-bali-luxe',
    authorName: 'Светлана Р.',
    authorEmail: 'svetlana@example.com',
    rating: 5,
    comment:
      'Маршрут был отточен до мелочей — от встречи в аэропорту до последнего ужина на пляже. Никакой спешки, только удовольствие.',
    status: 'approved',
    createdAt: '2026-03-09T08:00:00.000Z'
  },
  {
    id: 'rev-2',
    packageId: 'pkg-alps-premium',
    authorName: 'Амелия Т.',
    authorEmail: 'amelia@example.com',
    rating: 5,
    comment:
      'Прекрасный темп, отличный выбор отелей, а горный ужин стал самым запоминающимся моментом путешествия.',
    status: 'approved',
    createdAt: '2026-03-11T08:00:00.000Z'
  },
  {
    id: 'rev-3',
    packageId: 'pkg-iceland-fire-ice',
    authorName: 'Александр М.',
    authorEmail: 'alex@example.com',
    rating: 5,
    comment:
      'Северное сияние в первую же ночь — это незабываемо. Тур продуман до мелочей, гид невероятно знающий.',
    status: 'approved',
    createdAt: '2026-03-07T08:00:00.000Z'
  },
  {
    id: 'rev-4',
    packageId: 'pkg-morocco-design',
    authorName: 'Мария К.',
    authorEmail: 'maria@example.com',
    rating: 5,
    comment:
      'Марокко поразило нас с первого дня. Невероятные цвета, ароматы и теплота людей. Однозначно вернусь!',
    status: 'approved',
    createdAt: '2026-03-04T08:00:00.000Z'
  },
  {
    id: 'rev-5',
    packageId: 'pkg-norway-fjords',
    authorName: 'Дмитрий В.',
    authorEmail: 'dmitri@example.com',
    rating: 4,
    comment:
      'Фьорды потрясающие, трекинг сложный но того стоит. Рекомендую брать хорошую обувь и приходить подготовленным.',
    status: 'approved',
    createdAt: '2026-03-02T08:00:00.000Z'
  },
  {
    id: 'rev-6',
    packageId: 'pkg-thailand-islands',
    authorName: 'Анна С.',
    authorEmail: 'anna@example.com',
    rating: 5,
    comment:
      'Таиланд превзошёл все ожидания. Пляжи, еда, закаты — всё было идеальным. Организация на высшем уровне.',
    status: 'pending',
    createdAt: '2026-03-14T08:00:00.000Z'
  }
];

export const mockUsers: AppUser[] = [];
export const mockBookings: Booking[] = [];

export const mockStories: Story[] = [
  {
    id: 'story-1',
    submittedAt: '2026-05-10T10:32:00.000Z',
    status: 'published',
    publishedAt: '2026-05-12T09:00:00.000Z',
    rejectedAt: null,
    rejectionReason: null,
    rawAuthorName: 'Наталья К.',
    rawObject: 'Пансионат «Чайка», Анапа',
    rawPeriod: 'Июль 2025 · 12 дней',
    rawManager: 'Анна Петрова',
    rawText: 'Мы приехали всей семьёй — трое детей. Пансионат превзошёл все ожидания: чистое море прямо у входа, отличная анимация, дети были в восторге каждый день. Отдельное спасибо Анне — она подобрала нам идеальные даты и номер с видом на море.',
    photos: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80'],
    pubTitle: 'Море, арбузы и счастливые дети',
    pubQuote: 'Мы приехали всей семьёй — трое детей. Пансионат превзошёл все ожидания: чистое море прямо у входа, отличная анимация.',
    pubTag: 'Семейный отдых',
    pubTagId: 'tag-family',
    pubObjectUrl: '/objects/chaika-anapa',
  },
  {
    id: 'story-2',
    submittedAt: '2026-05-14T14:22:00.000Z',
    status: 'published',
    publishedAt: '2026-05-15T10:00:00.000Z',
    rejectedAt: null,
    rejectionReason: null,
    rawAuthorName: 'Елена В.',
    rawObject: 'Санаторий «Дюны», Анапа',
    rawPeriod: 'Август 2025 · 10 дней',
    rawManager: '',
    rawText: 'Чёрное море в августе — это просто сказка. Тёплая вода, великолепный закат с набережной, вкуснейшая рыба. Санаторий оказался намного лучше, чем на фото — просторные номера, уютная территория.',
    photos: ['https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=80'],
    pubTitle: 'Анапа в августе: тёплое море и закаты',
    pubQuote: 'Чёрное море в августе — это просто сказка. Тёплая вода, великолепный закат с набережной, вкуснейшая рыба.',
    pubTag: 'Пляж и море',
    pubTagId: 'tag-beach',
    pubObjectUrl: '/objects/duny-anapa',
  },
  {
    id: 'story-3',
    submittedAt: '2026-05-20T09:15:00.000Z',
    status: 'published',
    publishedAt: '2026-05-21T11:00:00.000Z',
    rejectedAt: null,
    rejectionReason: null,
    rawAuthorName: 'Ирина С.',
    rawObject: 'Санаторий «Горный воздух», Сочи',
    rawPeriod: 'Июнь 2025 · 14 дней',
    rawManager: 'Мария Соколова',
    rawText: 'Две недели в санатории с полным лечебным курсом. Вышла как новая — никакого стресса, прекрасный воздух, профессиональные врачи. Процедуры, прогулки по парку, выход к морю — идеальное восстановление.',
    photos: ['https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80'],
    pubTitle: '14 дней без стресса: велнес в Сочи',
    pubQuote: 'Вышла как новая — никакого стресса, прекрасный воздух, профессиональные врачи. Идеальное восстановление.',
    pubTag: 'Wellness и лечение',
    pubTagId: 'tag-wellness',
    pubObjectUrl: '/objects/gorny-vozduh-sochi',
  },
  {
    id: 'story-4',
    submittedAt: '2026-06-01T16:45:00.000Z',
    status: 'published',
    publishedAt: '2026-06-02T09:30:00.000Z',
    rejectedAt: null,
    rejectionReason: null,
    rawAuthorName: 'Андрей Г.',
    rawObject: 'Пансионат «Морской прибой», Туапсе',
    rawPeriod: 'Май 2025 · 7 дней',
    rawManager: 'Дмитрий Орлов',
    rawText: 'Сочи в мае — это совсем другой город. Без толпы, с цветущими магнолиями и комфортной погодой. Отличный вариант для пары: прогулки по набережной, горы рядом, вечерний джаз в кафе.',
    photos: ['https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=800&q=80'],
    pubTitle: 'Сочи в мае: магнолии и тишина',
    pubQuote: 'Сочи в мае — это совсем другой город. Без толпы, с цветущими магнолиями и комфортной погодой.',
    pubTag: 'Город и культура',
    pubTagId: 'tag-city',
    pubObjectUrl: '/objects/morskoy-priboy-tuapse',
  },
  {
    id: 'story-5',
    submittedAt: '2026-06-05T11:20:00.000Z',
    status: 'new',
    publishedAt: null,
    rejectedAt: null,
    rejectionReason: null,
    rawAuthorName: 'Светлана М.',
    rawObject: 'ДОЛ «Орлёнок»',
    rawPeriod: 'Июль 2025 · 21 день',
    rawManager: '',
    rawText: 'Наш сын впервые поехал в лагерь — мы очень переживали. Но вернулся совершенно другим человеком: стал смелее, завёл друзей со всей страны, научился кататься на сёрфе. Организация на высшем уровне, педагоги замечательные.',
    photos: [],
    pubTitle: null,
    pubQuote: null,
    pubTag: null,
    pubTagId: null,
    pubObjectUrl: null,
  },
  {
    id: 'story-6',
    submittedAt: '2026-06-01T09:00:00.000Z',
    status: 'published',
    publishedAt: '2026-06-02T10:00:00.000Z',
    rejectedAt: null,
    rejectionReason: null,
    rawAuthorName: 'Марина Д.',
    rawObject: 'Санаторий «Нарзан», Кисловодск',
    rawPeriod: 'Апрель 2025 · 14 дней',
    rawManager: 'Анна Петрова',
    rawText: 'Кисловодск поразил меня своей атмосферой. Нарзанные ванны, горный воздух и прогулки по Курортному бульвару — это настоящее исцеление для души и тела.',
    photos: ['https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=800&q=80'],
    pubTitle: 'Кисловодск: нарзан и горный воздух',
    pubQuote: 'Нарзанные ванны, горный воздух и прогулки по Курортному бульвару — настоящее исцеление для души и тела.',
    pubTag: 'Wellness и лечение',
    pubTagId: 'tag-wellness',
    pubObjectUrl: null,
  },
  {
    id: 'story-7',
    submittedAt: '2026-06-03T14:00:00.000Z',
    status: 'published',
    publishedAt: '2026-06-04T09:00:00.000Z',
    rejectedAt: null,
    rejectionReason: null,
    rawAuthorName: 'Павел К.',
    rawObject: 'ДОЛ «Орлёнок»',
    rawPeriod: 'Июль 2025 · 21 день',
    rawManager: '',
    rawText: 'Наша дочь вернулась из лагеря совершенно другим человеком. Открытая, уверенная, с кучей новых друзей. Вожатые профессиональные, программа насыщенная.',
    photos: ['https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?auto=format&fit=crop&w=800&q=80'],
    pubTitle: 'Лагерь, который меняет детей',
    pubQuote: 'Наша дочь вернулась совершенно другим человеком — открытой, уверенной, с кучей новых друзей.',
    pubTag: 'Детский лагерь',
    pubTagId: 'tag-camp',
    pubObjectUrl: null,
  },
  {
    id: 'story-8',
    submittedAt: '2026-06-05T11:00:00.000Z',
    status: 'published',
    publishedAt: '2026-06-06T09:00:00.000Z',
    rejectedAt: null,
    rejectionReason: null,
    rawAuthorName: 'Алексей В.',
    rawObject: 'База отдыха «Горный воздух», Архыз',
    rawPeriod: 'Май 2025 · 10 дней',
    rawManager: 'Дмитрий Орлов',
    rawText: 'Архыз в мае — это нечто особенное. Снег на вершинах, цветущие поляны внизу, чистейший воздух. Каждое утро треккинговый маршрут, каждый вечер — баня и звёздное небо.',
    photos: ['https://images.unsplash.com/photo-1454496522488-7a8e488e8606?auto=format&fit=crop&w=800&q=80'],
    pubTitle: 'Архыз: горы, снег и цветущие поляны',
    pubQuote: 'Снег на вершинах, цветущие поляны внизу. Каждое утро треккинг, каждый вечер баня и звёздное небо.',
    pubTag: 'Горы и природа',
    pubTagId: 'tag-mountains',
    pubObjectUrl: null,
  },
  {
    id: 'story-9',
    submittedAt: '2026-06-06T10:00:00.000Z',
    status: 'published',
    publishedAt: '2026-06-07T09:00:00.000Z',
    rejectedAt: null,
    rejectionReason: null,
    rawAuthorName: 'Ольга С.',
    rawObject: 'Гостиница «Прибой», Геленджик',
    rawPeriod: 'Июнь 2025 · 3 дня',
    rawManager: 'Анна Петрова',
    rawText: 'Три дня в Геленджике на длинные выходные — идеальный перезагруз. Небольшая поездка, а ощущение как после недельного отдыха. Рекомендую этот формат всем, кто работает без отпуска.',
    photos: ['https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=80'],
    pubTitle: 'Геленджик на три дня: лучший перезагруз',
    pubQuote: 'Три дня — а ощущение как после недельного отдыха. Идеальный формат для тех, кто работает без отпуска.',
    pubTag: 'Выходного дня',
    pubTagId: 'tag-weekend',
    pubObjectUrl: null,
  },
  {
    id: 'story-10',
    submittedAt: '2026-06-07T08:00:00.000Z',
    status: 'published',
    publishedAt: '2026-06-08T09:00:00.000Z',
    rejectedAt: null,
    rejectionReason: null,
    rawAuthorName: 'Татьяна Р.',
    rawObject: 'Санаторий «Дюны», Анапа',
    rawPeriod: 'Август 2025 · 10 дней',
    rawManager: 'Мария Соколова',
    rawText: 'Второй раз приезжаем в «Дюны» и снова в восторге. Море тёплое, пляж чистый, персонал отличный. Дети купались по 6 часов в сутки — не вытащишь.',
    photos: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80'],
    pubTitle: 'Анапа снова покорила — едем второй раз',
    pubQuote: 'Второй раз в «Дюнах» и снова в восторге. Море тёплое, дети купались по 6 часов — не вытащишь.',
    pubTag: 'Пляж и море',
    pubTagId: 'tag-beach',
    pubObjectUrl: '/objects/duny-anapa',
  },
];

export const mockGalleryPhotos = [
  { src: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80', alt: 'Море, Анапа', span: 5, height: 300 },
  { src: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=80', alt: 'Путешествие', span: 4, height: 300 },
  { src: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=700&q=80', alt: 'Велнес', span: 3, height: 300 },
  { src: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=700&q=80', alt: 'Берег', span: 3, height: 220 },
  { src: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=900&q=80', alt: 'Семья на отдыхе', span: 6, height: 220 },
  { src: 'https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?auto=format&fit=crop&w=700&q=80', alt: 'Туризм', span: 3, height: 220 },
];
