name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 72.56.32.183
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: /home/deploy.sh
